# These are supported funding model platforms

github: [yourusername] # Replace with your GitHub username
open_collective: omnifusion-music # Replace with your Open Collective slug
ko_fi: omnifusionmusic # Replace with your Ko-fi username
tidelift: omnifusion-music # Replace with your Tidelift project name
community_bridge: omnifusion-music # Replace with your Community Bridge project name
liberapay: omnifusionmusic # Replace with your Liberapay username
issuehunt: omnifusionmusic # Replace with your IssueHunt username
otechie: omnifusionmusic # Replace with your Otechie username
custom: ["https://paypal.me/omnifusionmusic", "https://buymeacoffee.com/omnifusionmusic", "https://omnifusionmusic.com/support"] 